In [1]:
import pandas as pd

In [2]:
vgsales = pd.read_csv('vgsales.csv')

In [3]:
vgsales.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [10]:
vgsales.Platform.value_counts()

DS      2163
PS2     2161
PS3     1329
Wii     1325
X360    1265
PSP     1213
PS      1196
PC       960
XB       824
GBA      822
GC       556
3DS      509
PSV      413
PS4      336
N64      319
SNES     239
XOne     213
SAT      173
WiiU     143
2600     133
GB        98
NES       98
DC        52
GEN       27
NG        12
WS         6
SCD        6
3DO        3
TG16       2
PCFX       1
GG         1
Name: Platform, dtype: int64

In [4]:
vgsales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  object
 5   Publisher     16540 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

In [5]:
jvc = pd.read_csv('jvc.csv')

In [6]:
jvc.head()

,Unnamed: 0,game_fr,game_en,platform,website_rating,public_rating,publishor/developer,release,type,classification,url,description
0,1,.hack//G.U. Last Recode,.hack//G.U. Last Recode,PS4,14/20,--/20,Bandai Namco Entertainment,03 Novembre 2017,RPG,+12 ans,http://www.jeuxvideo.com/jeux/ps4/jeu-674262/,"Au contraire d’autres titres, None ,''.hack'' ..."
1,2,.hack//G.U. Vol.1//Rebirth,.hack//G.U. Vol. 1//Rebirth,PS2,15/20,18.2/20,Bandai Namco CyberConnect2,Date de sortie inconnue,RPG,+7 ans,http://www.jeuxvideo.com/jeux/playstation-2-ps...,Avec plus de 20 œuvres de fiction sur de mult...
2,3,.hack//Infection Part 1,.hack//Infection: Part 1,PS2,15/20,15.1/20,CyberConnect2 Bandai,26 Mars 2004,RPG,+12 ans,http://www.jeuxvideo.com/jeux/playstation-2-ps...,S'appuyant sur la maxime « Mieux vaut tard qu...
3,4,.hack//Mutation Part 2,.hack//Mutation: Part 2,PS2,14/20,16.4/20,Bandai CyberConnect2,18 Juin 2004,RPG,+12 ans,http://www.jeuxvideo.com/jeux/playstation-2-ps...,Voici enfin le second volet de la quadrilogie...
4,5,.hack//Outbreak Part 3,.hack//Outbreak: Part 3,PS2,13/20,15.3/20,CyberConnect2 Atari,17 Septembre 2004,RPG,+12 ans,http://www.jeuxvideo.com/jeux/playstation-2-ps...,Comme la maxime «Jamais deux sans trois» ne c...

In [7]:
jvc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17841 entries, 0 to 17840
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           17841 non-null  int64
 1   game_fr              17839 non-null  object
 2   game_en              17840 non-null  object
 3   platform             17841 non-null  object
 4   website_rating       17841 non-null  object
 5   public_rating        17841 non-null  object
 6   publishor/developer  17841 non-null  object
 7   release              17841 non-null  object
 8   type                 17841 non-null  object
 9   classification       17841 non-null  object
 10  url                  17841 non-null  object
 11  description          17607 non-null  object
dtypes: int64(1), object(11)
memory usage: 1.6+ MB

In [11]:
jvc.platform.value_counts()

PC             4255
PS2            1622
360            1417
PS3            1286
DS             1111
               ...
PC Mac 3DO        1
PC 3DS            1
PC iOS            1
3DS New 3DS       1
Switch WiiU       1
Name: platform, Length: 107, dtype: int64

In [13]:
vgsales = vgsales.rename(columns={'Name': 'game_en', 'Platform': 'platform'})

In [16]:
new_df = pd.merge(vgsales, jvc, on=['game_en', 'platform'])

In [17]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4140 entries, 0 to 4139
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Rank                 4140 non-null   int64
 1   game_en              4140 non-null   object
 2   platform             4140 non-null   object
 3   Year                 4079 non-null   float64
 4   Genre                4140 non-null   object
 5   Publisher            4135 non-null   object
 6   NA_Sales             4140 non-null   float64
 7   EU_Sales             4140 non-null   float64
 8   JP_Sales             4140 non-null   float64
 9   Other_Sales          4140 non-null   float64
 10  Global_Sales         4140 non-null   float64
 11  Unnamed: 0           4140 non-null   int64
 12  game_fr              4140 non-null   object
 13  website_rating       4140 non-null   object
 14  public_rating        4140 non-null   object
 15  publishor/developer  4140 non-null   object
 16  release              4140 non-null   object
 17  type                 4140 non-null   object
 18  classification       4140 non-null   object
 19  url                  4140 non-null   object
 20  description          4125 non-null   object
dtypes: float64(6), int64(2), object(13)
memory usage: 711.6+ KB

In [20]:
new_df.head()

,Rank,game_en,platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,...,Unnamed: 0,game_fr,website_rating,public_rating,publishor/developer,release,type,classification,url,description
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,...,17126,Wii Sports,14/20,13.7/20,Nintendo,08 Décembre 2006,Party-Game Sport,+7 ans,http://www.jeuxvideo.com/jeux/wii/00016407-wii...,Wii Sports est un jeu atypique. Il revendique...
1,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,...,8957,Mario Kart Wii,16/20,17.4/20,Nintendo,11 Avril 2008,Course,+3 ans,http://www.jeuxvideo.com/jeux/wii/00019173-mar...,"A lui seul, Mario Kart Wii pourrait bien boos..."
2,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,...,17128,Wii Sports Resort,15/20,16.4/20,Nintendo,24 Juillet 2009,Party-Game Sport,+3 ans,http://www.jeuxvideo.com/jeux/wii/00025771-wii...,"Fin 2006, Wii Sports accompagnait la Wii pour..."
3,6,Tetris,GB,1989.0,Puzzle,Nintendo,23.20,2.26,4.22,0.58,...,15008,Tetris,19/20,20/20,EA Mobile Nintendo AxySoft Bullet Proof Softwa...,1987,Réflexion Puzzle-Game Autres,+3 ans,http://www.jeuxvideo.com/jeux/jeu-82467/,Noé et son déluge n’ont pas le monopole de la...
4,7,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,11.38,9.23,6.50,2.90,...,10411,New Super Mario Bros.,17/20,17.4/20,Nintendo,30 Juin 2006,Plate-Forme,+3 ans,http://www.jeuxvideo.com/jeux/nintendo-ds/0001...,Après des années de bons et loyaux services s...

In [1]:
from sklearn.metrics import pairwise_distances

In [3]:
import numpy as np

In [5]:
A = np.array([[1, 2], [3, 6]])

In [6]:
A

array([[1, 2],
       [3, 6]])

In [7]:
pairwise_distances(A, metric='cosine')

array([[0.00000000e+00, 1.11022302e-16],
       [1.11022302e-16, 0.00000000e+00]])

In [1]:
(5/6)*(4/6)*(3/6)*(2/6)*(1/6)

0.015432098765432098